"""new attributes from loading refactor

Revision ID: fecce7565c14
Revises: f03d4b2033d1
Create Date: 2024-07-08 18:24:18.131716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fecce7565c14'
down_revision: Union[str, None] = 'f03d4b2033d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('ea_id', sa.Integer(), nullable=False))
    op.add_column('playerseasonblockingstats', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'playerseasonblockingstats', type_='foreignkey')
    op.create_foreign_key(None, 'playerseasonblockingstats', 'team', ['team_id'], ['id'])
    op.drop_column('playerseasonblockingstats', 'class_id')
    op.drop_column('playerseasonblockingstats', 'school_id')
    op.drop_column('playerseasonblockingstats', 'position_id')
    op.add_column('playerseasondefensestats', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'playerseasondefensestats', type_='foreignkey')
    op.create_foreign_key(None, 'playerseasondefensestats', 'team', ['team_id'], ['id'])
    op.drop_column('playerseasondefensestats', 'class_id')
    op.drop_column('playerseasondefensestats', 'school_id')
    op.drop_column('playerseasondefensestats', 'position_id')
    op.add_column('playerseasonkickingstats', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'playerseasonkickingstats', type_='foreignkey')
    op.create_foreign_key(None, 'playerseasonkickingstats', 'team', ['team_id'], ['id'])
    op.drop_column('playerseasonkickingstats', 'position_id')
    op.drop_column('playerseasonkickingstats', 'school_id')
    op.drop_column('playerseasonkickingstats', 'class_id')
    op.add_column('playerseasonoffensestats', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'playerseasonoffensestats', type_='foreignkey')
    op.create_foreign_key(None, 'playerseasonoffensestats', 'team', ['team_id'], ['id'])
    op.drop_column('playerseasonoffensestats', 'class_id')
    op.drop_column('playerseasonoffensestats', 'school_id')
    op.drop_column('playerseasonoffensestats', 'position_id')
    op.add_column('playerseasonreturnstats', sa.Column('team_id', sa.Integer(), nullable=False))
    op.drop_constraint(None, 'playerseasonreturnstats', type_='foreignkey')
    op.create_foreign_key(None, 'playerseasonreturnstats', 'team', ['team_id'], ['id'])
    op.drop_column('playerseasonreturnstats', 'class_id')
    op.drop_column('playerseasonreturnstats', 'school_id')
    op.drop_column('playerseasonreturnstats', 'position_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playerseasonreturnstats', sa.Column('position_id', sa.INTEGER(), nullable=False))
    op.add_column('playerseasonreturnstats', sa.Column('school_id', sa.INTEGER(), nullable=False))
    op.add_column('playerseasonreturnstats', sa.Column('class_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'playerseasonreturnstats', type_='foreignkey')
    op.create_foreign_key(None, 'playerseasonreturnstats', 'school', ['school_id'], ['id'])
    op.drop_column('playerseasonreturnstats', 'team_id')
    op.add_column('playerseasonoffensestats', sa.Column('position_id', sa.INTEGER(), nullable=False))
    op.add_column('playerseasonoffensestats', sa.Column('school_id', sa.INTEGER(), nullable=False))
    op.add_column('playerseasonoffensestats', sa.Column('class_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'playerseasonoffensestats', type_='foreignkey')
    op.create_foreign_key(None, 'playerseasonoffensestats', 'school', ['school_id'], ['id'])
    op.drop_column('playerseasonoffensestats', 'team_id')
    op.add_column('playerseasonkickingstats', sa.Column('class_id', sa.INTEGER(), nullable=False))
    op.add_column('playerseasonkickingstats', sa.Column('school_id', sa.INTEGER(), nullable=False))
    op.add_column('playerseasonkickingstats', sa.Column('position_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'playerseasonkickingstats', type_='foreignkey')
    op.create_foreign_key(None, 'playerseasonkickingstats', 'school', ['school_id'], ['id'])
    op.drop_column('playerseasonkickingstats', 'team_id')
    op.add_column('playerseasondefensestats', sa.Column('position_id', sa.INTEGER(), nullable=False))
    op.add_column('playerseasondefensestats', sa.Column('school_id', sa.INTEGER(), nullable=False))
    op.add_column('playerseasondefensestats', sa.Column('class_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'playerseasondefensestats', type_='foreignkey')
    op.create_foreign_key(None, 'playerseasondefensestats', 'school', ['school_id'], ['id'])
    op.drop_column('playerseasondefensestats', 'team_id')
    op.add_column('playerseasonblockingstats', sa.Column('position_id', sa.INTEGER(), nullable=False))
    op.add_column('playerseasonblockingstats', sa.Column('school_id', sa.INTEGER(), nullable=False))
    op.add_column('playerseasonblockingstats', sa.Column('class_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'playerseasonblockingstats', type_='foreignkey')
    op.create_foreign_key(None, 'playerseasonblockingstats', 'school', ['school_id'], ['id'])
    op.drop_column('playerseasonblockingstats', 'team_id')
    op.drop_column('player', 'ea_id')
    # ### end Alembic commands ###
